# Retrieve the title and total revenue generated by each film.
use sakila;

select
	title
    ,sum(amount) as total_revenue
from
	film f
    join inventory i on i.film_id = f.film_id
    join rental r on r.inventory_id = i.inventory_id
	join payment p on p.rental_id = r.rental_id
group by
	title
order by
	total_revenue desc
    ,title